-- 1. Creación de la base de datos si no existe
CREATE DATABASE IF NOT EXISTS tienda_db 
CHARACTER SET utf8mb4 
COLLATE utf8mb4_unicode_ci;

USE tienda_db;

-- 2. Limpieza de tablas previas (por si volvéis a reejecutar el script)
DROP TABLE IF EXISTS PEDIDO;
DROP TABLE IF EXISTS CARRITO;
DROP TABLE IF EXISTS PRODUCTO;
DROP TABLE IF EXISTS CLIENTE;

-- 3. Tabla CLIENTE
CREATE TABLE CLIENTE (
    ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    CONTRASEÑA VARCHAR(255) NOT NULL,
    TELEFONO VARCHAR(20)
) ENGINE=InnoDB;

-- 4. Tabla PRODUCTO
CREATE TABLE PRODUCTO (
    ID_PRODUCTO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    DESCRIPCION TEXT,
    STOCK INT NOT NULL DEFAULT 0,
    PRECIO DECIMAL(10,2) NOT NULL
) ENGINE=InnoDB;

-- 5. Tabla CARRITO (Relación N:M entre CLIENTE y PRODUCTO)
CREATE TABLE CARRITO (
    ID_CARRITO INT AUTO_INCREMENT PRIMARY KEY,
    ID_CLIENTE INT NOT NULL,
    ID_PRODUCTO INT NOT NULL,
    CANTIDAD INT NOT NULL DEFAULT 1,
    CONSTRAINT fk_carrito_cliente FOREIGN KEY (ID_CLIENTE) 
        REFERENCES CLIENTE(ID_CLIENTE) ON DELETE CASCADE,
    CONSTRAINT fk_carrito_producto FOREIGN KEY (ID_PRODUCTO) 
        REFERENCES PRODUCTO(ID_PRODUCTO) ON DELETE CASCADE
) ENGINE=InnoDB;

-- 6. Tabla PEDIDO (Relación N:M entre CLIENTE y PRODUCTO)
CREATE TABLE PEDIDO (
    ID_PEDIDO INT AUTO_INCREMENT PRIMARY KEY,
    ID_CLIENTE INT NOT NULL,
    ID_PRODUCTO INT NOT NULL,
    CANTIDAD INT NOT NULL DEFAULT 1,
    FECHA DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pedido_cliente FOREIGN KEY (ID_CLIENTE) 
        REFERENCES CLIENTE(ID_CLIENTE) ON DELETE CASCADE,
    CONSTRAINT fk_pedido_producto FOREIGN KEY (ID_PRODUCTO) 
        REFERENCES PRODUCTO(ID_PRODUCTO) ON DELETE RESTRICT
) ENGINE=InnoDB;